### ISSUE TITLE
Conflict with dependencies.

### ISSUE THREAD

**Issue by gegorov** [TheodoreGC/stylelint-plugin-license-header#5]
is there any chance that you can update stylelint to latest version? I have a conflict of dependencies of old stylelint. htmlparser-2 in particular.

**Comment by TheodoreGC** [comment]
Hi @gegorov, the version of `stylelint` used by the plugin has been updated to its latest and the plugin's version bumped to `1.0.3`.

You can refer to the [npm page of the plugin](https://www.npmjs.com/package/stylelint-plugin-license-header) for more details.
